# Import all the models so that Base has them before being imported by Alembic
from app.db.session import Base
from app.models.user_type import UserType
from app.models.user import User
from app.models.chat import Chat
from app.models.message import Message
from app.models.document import Document
from app.models.course import Course
from app.models.lesson import Lesson
from app.models.topic import Topic
from app.models.quiz import Quiz
from app.models.question import Question
from app.models.question_option import QuestionOption
from app.models.quiz_attempt import QuizAttempt
from app.models.quiz_answer import QuizAnswer
from app.models.user_stat import UserStat
from app.models.user_streak import UserStreak
from app.models.user_topic_progress import UserTopicProgress
from app.models.admin import AdminLog